version: 2

jobs:
  build_express_app:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Restore npm dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build app
          command: npm run build:prod

  build_angular_app:
    docker:
      - image: circleci/node:7.10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "ng/package.json" }}
          - v1-dependencies-
      - run:
          name: Restore npm dependencies
          working_directory: ng
          command: npm install
      - save_cache:
          paths:
            - ng/node_modules
          key: v1-dependencies-{{ checksum "ng/package.json" }}
      - run:
          name: Run unit tests
          working_directory: ng
          command: npm run test:ci
      - run:
          name: Send test coverage report to Coveralls.io
          working_directory: ng
          command: node node_modules/coveralls/bin/coveralls.js < coverage/lcov.info


workflows:
  version: 2

  Build:
    jobs:
      - build_express_app
      - build_angular_app
